config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'

  get 'menus/new'

  get 'menus/create'

  get 'menus/update'

  get 'menus/edit'

  get 'menus/destroy'

  mount Ckeditor::Engine => '/ckeditor'
  resources :categories, only: [:show]
  
  resources :pages, only: [:show]

  namespace :admin do
    resources :pages
    resources :categories
  end
  
  Page.where.not("slug", nil).all.each do |page|
    get "/#{page.slug}", controller: "pages", action: "show", id: page.id
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base
    validates_presence_of :name
    has_many :menu_items
    
    accepts_nested_attributes_for :menu_items, reject_if: :all_blank
    
end

app/controllers/admin/menus_controller.rb
module Admin
  class MenusController < ApplicationController
    def index
      @menus = Menu.all
    end
  
    def new
      @menu = Menu.new
      10.times { @menu.menu_items.build }
    end
  
    def create
      @menu = Menu.new menu_params
      if @menu.save
        redirect_to admin_menus_path, notice: "Menu created."
      else
        render :new
      end
    end
  
    def update
      @menu = Menu.find params[:id]
      if @menu.update_attributes menu_params
        redirect_to admin_menus_path, notice: "Menu updated."
      else
        render :edit
      end
    end
  
    def edit
      @menu = Menu.find params[:id]
      10.times { @menu.menu_items.build }
    end
  
    def destroy
      @menu = Menu.find params[:id]
      if @menu.destroy
        redirect_to admin_menus_path, notice: "Menu deleted."
      else
        redirect_to admin_menus_path, alert: "Menu was not deleted."
      end
    end
    
    protected
      def menu_params
        params.require(:menu).permit(:name, :menu_items_attributes => [ :title, :url, :id] )
      end
    
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/admin/menus/_form.html.haml
=form_for [ "admin", @menu ] do |f|
  %p
    =f.text_field :name

  %h3 Menu items
  =f.fields_for :menu_items do |c|
    %p
      =c.text_field :title
      =c.text_field :url
      =c.hidden_field :id

  %p
    =f.submit

app/views/admin/menus/edit.html.haml
%h1 Menus#edit
%p Find me in app/views/menus/edit.html.haml

app/views/admin/menus/index.html.haml
%h1 Menus

%ul
    -@menus.each do |menu|
        %li
            =menu.name
            =link_to "edit", edit_admin_menu_path(menu)
            %ul
                -menu.menu_items.each do |item|
                %li=link_to item.title, url_for_menu_item(item)
%p
  =link_to "New Menu", new_admin_menu_path

app/views/admin/menus/new.html.haml
%h1 Menus#new
%p Find me in app/views/menus/new.html.haml